stages:
- build_image

build_image:
  image: docker:latest
  stage: build_image
  services:
    - docker:dind
  script:
    - if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then export DOCKER_HOST="tcp://localhost:2375"; fi
    - export DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME/\//-}
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - source ./build.properties
    - docker build
      --label "GIT_COMMIT=$CI_COMMIT_SHA"
      -t "$DOCKER_IMAGE_REPOSITORY:$DOCKER_IMAGE_TAG" .
    - docker tag "$DOCKER_IMAGE_REPOSITORY:$DOCKER_IMAGE_TAG" "$CI_REGISTRY/$DOCKER_IMAGE_REPOSITORY:$DOCKER_IMAGE_TAG"
    - docker push "$CI_REGISTRY/$DOCKER_IMAGE_REPOSITORY:$DOCKER_IMAGE_TAG"

